version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm build
      - echo 'Build complete, running tests'
      - npm test

reports:
  jest_reports:
    files:
      - junit.xml
    file-format: JUNITXML
    base-directory: tests/
  clover_reports:
    files:
      - coverage/clover.xml
    fileFormat: CLOVERXML
