version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm build
      - echo 'Build complete, running tests'
      - npm test

reports:
  jest_reports:
    base-directory: tests/
    files:
      - junit.xml
    file-format: JUNITXML
  clover_reports_coverage:
    base-directory: coverage/
    files:
      - clover.xml
    file-format: CLOVERXML
