version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm build
      - echo 'Build complete, running tests'
      - npm test

reports:
  TEST:
    jest_reports:
      files:
        - junit.xml
      file-format: JUNITXML
      base-directory: tests/
  CODE_COVERAGE:
    clover_reports:
      files:
        - coverage/clover.xml
      file-format: CLOVERXML
