version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm build
      - npm test

reports:
  jest_reports:
    files:
      - junit.xml
    file-format: JUNITXML
    base-directory: /tests/
  clover_reports:
    files:
      - clover.xml
    fileFormat: CLOVERXML
    base-directory: /coverage/
